### ISSUE TITLE
Consider adding support for Configuration Cache

### ISSUE THREAD

**Issue by NicklasWallgren** [form-com/diff-coverage-gradle#57]
Consider adding support for https://docs.gradle.org/current/userguide/configuration_cache.html

Current issue;
https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

```
13 problems were found storing the configuration cache, 1 of which seems unique.
- Task `:diffCoverage` of type `com.form.coverage.gradle.DiffCoverageTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
````

```
Caused by: org.gradle.api.InvalidUserCodeException: Invocation of 'Task.project' by task ':diffCoverage' at execution time is unsupported.
        at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onTaskExecutionAccessProblem(ConfigurationCacheProblemsListener.kt:74)
        at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onProjectAccess(ConfigurationCacheProblemsListener.kt:53)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:464)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:446)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:61)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:434)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:221)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:192)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy1/jdk.proxy1.$Proxy174.onProjectAccess(Unknown Source)
        at org.gradle.api.internal.AbstractTask.notifyProjectAccess(AbstractTask.java:1053)
        at org.gradle.api.internal.AbstractTask.getProject(AbstractTask.java:237)
        at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)
        at com.form.coverage.gradle.DiffCoverageTask.getOutputDir(DiffCoverageTask.kt:45)
        at com.form.coverage.gradle.DiffCoverageTask.executeAction(DiffCoverageTask.kt:56)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

**Comment by SurpSG** [comment]
Hi @NicklasWallgren 

Could you try a snapshot with fixes
```
classpath 'com.github.form-com.diff-coverage-gradle:diff-coverage:support-configuration-cache-SNAPSHOT'
```
?

**Comment by NicklasWallgren** [comment]
Great, seems to work perfectly!

Thanks.

**Comment by NicklasWallgren** [comment]
@SurpSG Did you delete the SNAPSHOT?

**Comment by SurpSG** [comment]
Seems, snapshots are automatically removed after some time from jitpack and I cannot restore the artifacts :(

Please, wait for official release to use the feature

**Comment by hegyibalint** [comment]
@SurpSG was this solved by #63 ?

**Comment by SurpSG** [comment]
Hi @NicklasWallgren 
Seems this project is not maintained anymore 

You can switch to https://github.com/gw-kit/delta-coverage-plugin
